### ISSUE TITLE
Suggestion: accuracy interval and verbosity suppresion

### ISSUE THREAD

**Issue by brunolnetto** [rsalmei/human-repr#2]
"There is heat and light, and both waves our regards."

I read your development content enthusiastically. Often, there are many branches to visit. Our developer's job is to suppress this branch cardinality to offer intellectual empowerment. To bring value means to comprehend the tree elements it belongs to and enjoy the forest instead of zooming in on each. 

In this regard, I suggest to:

1. Add [confidence-interval-like feature](https://en.wikipedia.org/wiki/Propagation_of_uncertainty);
2. Reduce example verbosity by pattern `["sample-code", "use-instructions", "expected-behaviour"]`

**Comment by rsalmei** [comment]
Thanks for your insights Bruno, but those are out of the scope here...
This crate's purpose is to generate representations, as beautiful as they can be, which implies simplicity.
